/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EVIXMintRedeem__factory } from "./EVIXMintRedeem__factory";
export { IOracle__factory } from "./IOracle__factory";
